-- fast_hash columns and indexes are created idempotently by
-- ensure_fast_hash_columns() after migrations run. Keeping this migration
-- as a version marker prevents duplicate-column failures on repaired DBs.
